runtime: python310
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.6
  max_concurrent_requests: 80

handlers:
- url: /
  script: auto
env_variables:
  SEED_TOKEN: "massive-gcp-secret-token"
  SESSION_SECRET: "une-cle-de-session-tres-secrete-pour-flask"
